In [1]:
import pickle
with open('Scaler_stds.pickle', 'rb') as file:
    Scaler_stds = pickle.load(file)

In [2]:
Scaler_stds

array([1.12090715e+05, 6.67107854e+00, 4.07732570e+00, 1.35973854e-01,
       8.15516196e-02, 2.21770652e+00, 3.04654967e+00, 1.00000000e+00])

In [3]:
with open('Scaler_means.pickle', 'rb') as file:
    Scaler_means = pickle.load(file)

In [4]:
Scaler_means

array([1.61865794e+05, 1.39217333e+03, 1.08813333e+01, 9.86666667e-01,
       1.00400000e+00, 4.66666667e+00, 7.03466667e+00, 1.00000000e+00])

In [5]:
with open('model.pkl', 'rb') as file:
    model = pickle.load(file)

In [6]:
model

LinearRegression()

In [7]:
with open('Labels.pickle', 'rb') as file:
    Labels = pickle.load(file)

In [8]:
Labels

{'Color': {'آبی': 0,
  'آلبالویی': 1,
  'بادمجانی': 2,
  'بژ': 3,
  'تیتانیوم': 4,
  'خاکستری': 5,
  'دلفینی': 6,
  'ذغالی': 7,
  'زیتونی': 8,
  'سبز': 9,
  'سفید': 10,
  'سفید صدفی': 11,
  'طوسی': 12,
  'قرمز': 13,
  'قهوه\u200cای': 14,
  'مشکی': 15,
  'نقرآبی': 16,
  'نقره\u200cای': 17,
  'نوک\u200cمدادی': 18,
  'پوست\u200cپیازی': 19,
  'گیلاسی': 20,
  'یشمی': 21},
 'Engine': {'تعویض شده': 0, 'سالم': 1, 'نیاز به تعمیر': 2},
 'Chassis': {'رنگ\u200cشده': 0, 'سالم و پلمپ': 1, 'ضربه\u200cخورده': 2},
 'Body': {'تصادفی': 0,
  'تمام\u200cرنگ': 1,
  'خط و خش جزیی': 2,
  'دوررنگ': 3,
  'رنگ\u200cشدگی': 4,
  'رنگ\u200cشدگی، در 1 ناحیه': 5,
  'رنگ\u200cشدگی، در 2 ناحیه': 6,
  'سالم و بی\u200cخط و خش': 7,
  'صافکاری بی\u200cرنگ': 8},
 'Gearbox': {'اتوماتیک': 0, 'دنده\u200cای': 1}}

In [9]:
with open('cols.pickle', 'rb') as file:
    cols = pickle.load(file)

In [10]:
from sklearn.preprocessing import StandardScaler

# Create a StandardScaler object
scaler = StandardScaler()
# Set new parameter values
new_params = {'with_mean': Scaler_means, 'with_std': Scaler_stds}
scaler.set_params(**new_params)

StandardScaler(with_mean=array([1.61865794e+05, 1.39217333e+03, 1.08813333e+01, 9.86666667e-01,
       1.00400000e+00, 4.66666667e+00, 7.03466667e+00, 1.00000000e+00]),
               with_std=array([1.12090715e+05, 6.67107854e+00, 4.07732570e+00, 1.35973854e-01,
       8.15516196e-02, 2.21770652e+00, 3.04654967e+00, 1.00000000e+00]))

In [29]:
from sklearn.preprocessing import scale                                 
import numpy as np

def prediction():
    y = []
    for item in cols:
        if item == 'Price':
            break
        if item in Labels.keys():
            for key, value in Labels[item].items():
                print("{} : {}".format(value, key) , end=" *\t* ")
            print()
            print(20*"-")
        x = int(input('for {} enter number: '.format(item)))
        y.append(x)
    print("inputs : ",y)
    scaled_data = scale(np.array(y), with_mean=list(Scaler_means), with_std=list(Scaler_stds))
    print("scaled data : ",scaled_data)
    return model.predict(scaled_data.reshape(1, -1))
    #model.predict(y)
    


In [16]:
y = [100,1398,1,1,1,1,1,1]
scale(np.array(y), with_mean=list(Scaler_means), with_std=list(Scaler_stds))

array([-0.19193705,  2.63913451, -0.40786624, -0.40786624, -0.40786624,
       -0.40786624, -0.40786624, -0.40786624])

In [31]:
p = prediction()

KeyboardInterrupt: Interrupted by user

In [32]:
print("price prediction : ",p)

price prediction :  [226.80667661]
